name: Pull Requests CI

# Run on pull requests to master branch
on:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit_tests:
    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    # The specific container to use
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    # https://hub.docker.com/r/hseeberger/scala-sbt/
    container: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Run unit tests
      - name: Run Unit Tests
        run: sbt "clean;compile;test"

  assemble:
    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    # The specific container to use
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    # https://hub.docker.com/r/hseeberger/scala-sbt/
    container: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Assembly artifact
      - name: Create Assembly
        run: sbt stage

      # Upload jar as build artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cicd-series-assembly.jar
          path: target/scala-2.13/cicd-series-assembly-0.1.0-SNAPSHOT.jar

  pats:
    runs-on: ubuntu-latest
    container: openkbs/jre-mvn-py3:v1.0.6
    needs: assemble

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Download artifact
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: cicd-series-assembly.jar

      # Verify artifact
      - name: List Files
        run: ls -al

      # This is needed because the artifact is downloaded with the original file name (includes version)
      - name: Rename Artifact
        run: mv cicd-series-assembly-*.jar cicd-series-assembly.jar

      # This is needed because download artifacts are not runnable
      - name: Change Permissions
        run: chmod a+rx cicd-series-assembly.jar

      # Verify artifact
      - name: List Files
        run: ls -al

      # Install python dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Run behave tests
      - name: Run PATs
        run: behave

  # Terraform setup copied from
  # https://github.com/hashicorp/setup-terraform
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Give default URL so the plan works, however this version will not be deployed
      - name: Terraform Plan
        id: plan
        run: |
          export TF_VAR_build_url="https://github.com/DWiechert/cicd-series/releases/tag/0.0.1.tar.gz"
          terraform plan -no-color

      - name: Terraform Report
        id: report
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })